# Generated by Django 4.2.6 on 2023-10-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='static/images/about_us/carousal')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_images', models.ImageField(upload_to='static/images/blog')),
                ('blog_data', models.TextField(max_length=1000)),
                ('blog_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('meeting_format', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=100)),
                ('meeting_agenda', models.CharField(max_length=50)),
                ('additional_questions', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_email', models.EmailField(max_length=100)),
                ('job_mobile', models.CharField(max_length=200)),
                ('job_profile', models.CharField(max_length=500)),
                ('job_experience', models.CharField(max_length=200)),
                ('job_cv', models.FileField(blank=True, null=True, upload_to='job_applications/')),
            ],
        ),
    ]
